export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Unlimited Transactions with zero fees",
    description: "Get access to our exclusives app that allows you to send unlimited...",
    buttonLabel: "Get Started",
    imgStart: true,
    img: require("../../images/svg-1.svg").default,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Unlimited Transactions with zero fees",
    description: "Get access to our exclusives app that allows you to send unlimited...",
    buttonLabel: "Get Started",
    imgStart: false,
    img: require("../../images/svg-1.svg").default,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headline: "Unlimited Transactions with zero fees",
    description: "Get access to our exclusives app that allows you to send unlimited...",
    buttonLabel: "Get Started",
    imgStart: true,
    img: require("../../images/svg-1.svg").default,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
}